Fix scroll upshot in voila rendering context
bloomberg/ipydatagrid pull request #272
Opened 2021-09-26 21:49 UTC by ibdafna

Signed-off-by: Itay Dafna <i.b.dafna@gmail.com>

2021-09-26 22:14 UTC, gaborbernat submitted a review, later dismissed

2021-09-26 22:15 UTC, ibdafna commented
@gaborbernat I saw some Python test suite failures on versions >3.6 and re-triggered the tests. I can't reproduce locally. Also this code change should not affect the Python side.

2021-09-26 22:22 UTC, ibdafna commented
@martinRenou looks related to your PR in jupyter_client:

https://github.com/jupyter/jupyter_client/commit/1363f53f308f0d3621950dcbd2e49edd89ab4aa6

2021-09-26 22:38 UTC, ibdafna commented
EDIT: I can now reproduce locally with a fresh environment and python=3.9.

2021-09-30 06:57 UTC, ibdafna commented
Discussed this with @martinRenou. We will fix the serialisation issue in `ipywidgets`, and in the meantime I will pin `jupyter_client` to version 6.2.0.

2021-09-30 07:05 UTC, SylvainCorlay commented
> Discussed this with @martinRenou. We will fix the serialisation issue in ipywidgets, and in the meantime I will pin jupyter_client to version 6.2.0.

@ibdafna are you still around?

2021-09-30 07:06 UTC, SylvainCorlay commented
It is probably not a good idea to support the case of tuple keys in the js serialization of ipykernel.

2021-09-30 07:09 UTC, ibdafna commented
@SylvainCorlay still around. I don't think there's a way around that for serialisation of nested-index pandas DataFrames. Why is it a bad idea? Tuples are immutable, and they can also be converted to string if necessary.

2021-09-30 07:10 UTC, SylvainCorlay commented
> @SylvainCorlay still around. I don't think there's a way around that for serialisation of nested-index pandas DataFrames. Why is it a bad idea? Tuples are immutable, and they can also be converted to string if necessary.

Walking over all JSON entries in ipykernel to find tuple keys is very inefficient.
It should probably be converted to string in the client code.

2021-09-30 08:32 UTC, gaborbernat submitted a review, later dismissed
![](https://media.tenor.co/images/22179354ce434e8d0d8b0aa83d3854a4/tenor.gif)

2021-09-30 09:15 UTC, martinRenou requested changes

2021-09-30 09:15 UTC, martinRenou commented on pyproject.toml
> +    "jupyter_client~=6.2.0"
This shouldn't be needed if https://github.com/bloomberg/ipydatagrid/pull/274 gets in

2021-10-01 16:07 UTC, kaiayoung approved these changes

2021-10-01 16:07 UTC, merged