Fix void zone click and column resize issues
bloomberg/ipydatagrid pull request #295
Opened 2022-02-18 19:02 UTC by ibdafna

2022-02-21 08:31 UTC, martinRenou requested changes

2022-02-21 08:31 UTC, martinRenou commented on tests/test_datagrid.py
> +    print(data_object)
Maybe a leftover?

2022-02-21 08:32 UTC, martinRenou commented
Looks good! We should probably upstream this `isResizing` getter

2022-02-21 09:56 UTC, gaborbernat approved these changes
![](https://media.tenor.co/images/bee8bf98cd1c1d9659af200f8aa71206/tenor.gif)

2022-02-21 10:06 UTC, gaborbernat approved these changes
![](https://media.tenor.co/images/bee8bf98cd1c1d9659af200f8aa71206/tenor.gif)

2022-02-23 17:08 UTC, ibdafna commented
Test failures in 3.7/3.6 due to pandas versions. Will update separately

2022-02-23 17:09 UTC, merged